sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull manabugt/android
  - docker run -v $(pwd)/:/opt/workspace/ manabugt/android /bin/sh build-travis.sh